disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Louis Fourquet"

[params]
  displayName = "Louis Fourquet"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "//"
  copyright = "Copyright"

[params.author]
  name = "Louis Fourquet"
  email = "louis.fourquet@gmail.com"
  image = "images/profile.jpg"
  imageQuality = 96
  headline = "Game Programmer | Unity | Unreal Engine | C# | C++"
  bio = "Game Developer"
  links = [
    { linkedin = "https://linkedin.com/in/louisfourquet" },
    { github = "https://github.com/4quet" },
    { itch-io = "https://4quet.itch.io" },
  ]
